version: "3"
services:
    test_web:
        image: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
          - test_application


    test_application:
        build: .
        expose:
          - 8080

volumes:
    test_volume:
